services:
  auth0:
    build:
      context: auth0
      dockerfile: Dockerfile
    image: scalis/mock-auth0
    networks:
      - scalis
    ports:
      - 5001:5001

networks:
  scalis:
    driver: bridge
